### ISSUE TITLE
Use kdesu or gksu

### ISSUE THREAD

**Issue by tuxayo** [p-eli/create_ap-gui#2]
(when available)
To be able to use the program without launching it from the terminal.

**Comment by p-eli** [comment]
Hi, on install process, is creating createApGui.desktop file in /usr/share/applications, that enable start program without launching from terminal, but it uses gksudo. This is only command that work on all system and desktop environment which was tested by me. If it doesn't work for you please send me system and desktop environment that you use.

**Comment by tuxayo** [comment]
Thanks it's already used indeed!
I use dmenu (on XFCE and Openbox) which scans the PATH so the .desktop is not there. I'm not sure if there is a way to make it search also in `/usr/share/applications` and use the .desktop :-(
